### ISSUE TITLE
Does tier price importer plugin work with Magento 2?

### ISSUE THREAD

**Issue by NudeWeb** [macopedia/magmi-m2#20]
Has anyone got a wroking version for Magento 2 to import tier/group prices?

**Comment by Boyd1e** [comment]
yes it is working, I have put in the change to make it work 
https://github.com/Boyd1e/magmi-m2

**Comment by simonrl** [comment]
Hi, it does not work for me. Can you post the code of your change so I can have a look at it? Using Magento 2.2.5

**Comment by Boyd1e** [comment]
its been a while i think it was this:

> /magmi/plugins/extra/itemprocessors/tierprice

Line 168
change "core_store" to "store"

save changes

**Comment by simonrl** [comment]
great, this was it - thanks!

as a side note, I replaced core_store everywhere in magmi and dropdown attribute import worked afterwards (also didn't work before).

**Comment by Boyd1e** [comment]
That's good news! Glad I could help! :)

**Comment by Boyd1e** [comment]
Can't say I have ever submitted anything to github (I signed up to share this), I have however submitted a commit a few minutes ago if that works?

**Comment by tmotyl** [comment]
Hi @Boyd1e there was sth wrong with the PR you've send (there were tons of commits). Please try again, or paste a link to a commit in your repo which fixes the problem.

**Comment by tmotyl** [comment]
@simonrl Sounds like you have fixed some other places too. Can you send a PR? thanks

**Comment by simonrl** [comment]
@tmotyl yes i can fork & provide a PR on Sunday.

**Comment by tmotyl** [comment]
awesome, thanks!

**Comment by max21** [comment]
Hi, can you please provide the pr for this issue ?

**Comment by tmotyl** [comment]
I've just merged the change, so closing the issue.
