### ISSUE TITLE
Magmi on Nginx

### ISSUE THREAD

**Issue by studioworx-meniconi** [macopedia/magmi-m2#23]
Hello, 

Ive used magmi in the past on magento 1 and apache server, but I'm fairly new to nginx and magento 2.
Im getting a 404 error when trying to access the /magmi/web/magmi.php I had a look here https://magento.stackexchange.com/questions/208225/how-do-i-install-the-magmi-for-magento-2-extension and follow the instructions there but still getting a 404, anybody have any idea?

Thanks in advance

**Comment by alex-79** [comment]
```    
    location /magmi {
        root $MAGE_ROOT;

	location ~ ^/magmi/.*\.php {
    	    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
    	    fastcgi_pass   fastcgi_backend_mamadecor;
    	    fastcgi_index  index.php;
    	    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    	    include        fastcgi_params;
	}

    }
```

**Comment by tmotyl** [comment]
I assume the answer from @alex-79 solved the issue. Let me know if it doesn;t

**Comment by giri-gta-repo** [comment]
> ```
>     location /magmi {
>         root $MAGE_ROOT;
> 
> 	location ~ ^/magmi/.*\.php {
>     	    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
>     	    fastcgi_pass   fastcgi_backend;
>     	    fastcgi_index  index.php;
>     	    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
>     	    include        fastcgi_params;
> 	}
> 
>     }
> ```

Where i can paste this code?
