### ISSUE TITLE
Variation addtion problem

### ISSUE THREAD

**Issue by shahidch85** [macopedia/magmi-m2#24]
When ever I tried to add Size as variation for configurable product it show following error...
 " Potential assignment problem, specific model found for select attribute => size(Magento\Eav\Model\Entity\Attribute\Source\Table) "

Anyone can help to solve this problem?

**Comment by ZieClaw** [comment]
I have found the reason for this issue, in magmi_productimportengine.php there is a check on line 333 that checks for eav/entity_attribute_source_table which is the old Magento 1 model.

Replace this with Magento\Eav\Model\Entity\Attribute\Source\Table and it should work.

**Comment by alesconti** [comment]
Thanks !

**Comment by tmotyl** [comment]
@ZieClaw can you please provide a pull request?

**Comment by tmotyl** [comment]
PR merged, thanks @ZieClaw
