### ISSUE TITLE
magmi installation - existing files .gitignore and composer.json

### ISSUE THREAD

**Issue by marco7319** [macopedia/magmi-m2#26]
Hello
I use magento 2.2.3.  If i install magmi 7.2.3 at root, i already have existing files: .gitignore and composer.json. included in the zip;
The installation will crush them. Is this normal?

**Comment by tmotyl** [comment]
@marco7319 
I have no idea how did you install magmi and what folder are you refering to.
I'm closing this issue as it has too little information to be able to reproduce it. Please reopen once you have more steps to reproduce it.
