### ISSUE TITLE
Imported product are not visible and can't enable after import 

### ISSUE THREAD

**Issue by gfxguru** [macopedia/magmi-m2#29]
// Provide a general summary of the issue in the Title above

### Preconditions
// Provide a more detailed information about you Magento, Apache2/nginx, PHP & MySQL version
// Provide example CSV file to help us reproduce your issue
1. Magento 2.2.5 / Apache 2.4/ Mysql 5.x
2. 
3. 

### Steps to reproduce
// Provide a list of steps to reproduce this bug, include which plugins you use
// You can attach your magmi profile files stored in directory "{your Magento dir}/magmi/conf/{your profile name directory}
1. 
2. 
3. 

### Actual result
// Tell us what happens instead - screenshot, logs etc.
1.

**Comment by gfxguru** [comment]
Actually, the products are imported and visible on category page but blank or white page when you click on products. Imported url is also not available. Any ideas?

**Comment by Kamik** [comment]
I have about the same problem. Products were imported, visible in the backend, also tied in categories. But on the category page  on frontend you can't see them. The category is empty. Import was with the plugin categories on fly

**Comment by Kamik** [comment]
Problem  comes from Smile Elastiksearch extension.

**Comment by Boyd1e** [comment]
this can also be caused by broken image links, for some reason it can import broken links which stop the catagory pages loading correctly.

**Comment by tmotyl** [comment]
Without steps to reproduce it, it cant be fixed. Please reopen once you have more data.
