### ISSUE TITLE
password for magmi magento 2

### ISSUE THREAD

**Issue by pratikkamani** [macopedia/magmi-m2#34]
I have successfully logged in on localhost with username and password: "magmi".
When this folder move to server, neither "magmi" nor my admin password was worked.

Also, I tried with a fresh magmi folder, for first-time "magmi" password doesn't work.
http://czargrou.wwwsg1-ss1.a2hosted.com/mustperfume/magmi/web/magmi.php
Is there another way to skip login?

**Comment by rakeshdonga** [comment]
http://installmagentourl/magmi/web/magmi.php and use default user: magmi paswd: magmi

You are good to go..

One thing more

go to magmi/inc/magmi_engine.php replace the one 511 line and replace else code and add you credential

else {
                $host = $this->getProp("DATABASE", "host", "localhost");
                $dbname = $this->getProp("DATABASE", "dbname", "magento");
                $user = $this->getProp("DATABASE", "user",'root');
                $pass = $this->getProp("DATABASE", "password",'root');
                $port = $this->getProp("DATABASE", "port", "3306");
            }

**Comment by jefflenz** [comment]
check your htaccess if you are using php fpm.  there's a comment in security.php which contains the lines you need to add to htaccess.

**Comment by jefflenz** [comment]
Here's the comment from security.php:

/*
     * php-cgi/fpm under Apache does not pass HTTP Basic user/pass to PHP by default
     * For this workaround to work, add these lines to your .htaccess file:
     * RewriteEngine On
     * RewriteCond %{HTTP:Authorization} ^(.+)$
     * RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
     * @see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/ServerBag.php#L47
     */
