### ISSUE TITLE
Fatal error: Uncaught PDOException in Magento 2.2.6

### ISSUE THREAD

**Issue by joell67** [macopedia/magmi-m2#36]
v0.7.23-git 

To reproduce the error, copy the files over to magento 2.2.6 root, then access Magmi as you normally would  (/magmi/web/magmi.php).

Page loads, you can insert credentials and save - but at the bottom of the page there is an error that reads:
(Note, actual credentials were removed from below error)

`Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection timed out in /magmi/inc/dbhelper.class.php:58 Stack trace: #0 /magmi/inc/dbhelper.class.php(58): PDO->__construct('mysql:host=192....', 'mtwotech_magim', 'SlitsClewsEider...', Array) #1 /magmi/inc/magmi_engine.php(518): DBHelper->initDb('127.0.0.1', 'db_name', 'db_user', 'password...', '3306', NULL, 'net', false) #2 /magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(35): Magmi_Engine->connectToMagento() #3 /magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(105): Magmi_ReindexingPlugin->initIndexList() #4 /magmi/plugins/base/general/reindex/options_panel.php(20): Magmi_ReindexingPlugin->getIndexList() #5 in /magmi/inc/dbhelper.class.php on line 58 `

Is this version (v0.7.23-git) compatible with 2.2.6 or I am missing something?

**Comment by tmotyl** [comment]
no, it's not.
You should use current master or at last version 200.7.23 
I will tag a new version from current master next week, as there were quite some changes since 200.7.23
