### ISSUE TITLE
SQLSTATE[HY000]: General error: 1364 Field 'parent_product_id' doesn't have a default value -

### ISSUE THREAD

**Issue by tonyabm** [macopedia/magmi-m2#38]
// Provide a general summary of the issue in the Title above

### Preconditions
// Provide a more detailed information about you Magento, Apache2/nginx, PHP & MySQL version
// Provide example CSV file to help us reproduce your issue
1.  Version: Magento 2.2.2
2.  Server: Aws bitnami
3.  CSV file: [https://docs.google.com/spreadsheets/d/1jQeiUpOtkx_38w2d-eJxSOQO-w5zlaOSGeK_6WbsA7k/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1jQeiUpOtkx_38w2d-eJxSOQO-w5zlaOSGeK_6WbsA7k/edit?usp=sharing)

### Steps to reproduce
// Provide a list of steps to reproduce this bug, include which plugins you use
// You can attach your magmi profile files stored in directory "{your Magento dir}/magmi/conf/{your profile name directory}
1.  bundle product import 
2.  create new one 

### Actual result
// Tell us what happens instead - screenshot, logs etc.
1. The error mesg:
`SKU G472-tony-sofia - 1 SQLSTATE[HY000]: General error: 1364 Field 'parent_product_id' doesn't have a default value -
SKU G472-tony-sofia - 2 SQLSTATE[HY000]: General error: 1364 Field 'parent_product_id' doesn't have a default value - ERROR ON RECORD #1
SKU G472-tony1-sofia - 3 SQLSTATE[HY000]: General error: 1364 Field 'parent_product_id' doesn't have a default value -
SKU G472-tony1-sofia - 4 SQLSTATE[HY000]: General error: 1364 Field 'parent_product_id' doesn't have a default value - ERROR ON RECORD #2 `

![image](https://user-images.githubusercontent.com/16289287/50419112-067e3200-086a-11e9-8992-8a53a719382b.png)

**Comment by tmotyl** [comment]
seems like related to https://github.com/dweeves/magmi-git/pull/575
probably the fix (if still relevant) will be similar

**Comment by tmotyl** [comment]
fixed in: https://github.com/macopedia/magmi-m2/commit/71fb4900dee5fc8ed53c7e881ae912b5c7e4dc4c
