### ISSUE TITLE
Getting Error When try to import default csv

### ISSUE THREAD

**Issue by Anantkprajapati** [macopedia/magmi-m2#41]
Getting Error Like 
SKU SKU001-H - 1 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'row_id' in 'field list' -
SKU SKU001-H - 2 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'row_id' in 'field list' - ERROR ON 

When try to import default Magmi CSV in Magmi 

Preconditions
Magento ver 2.2.6 

Actual result
Default CSV should be import

**Comment by tmotyl** [comment]
Hi @Anantkprajapati 
can you please attach the csv file you're using? I'm not sure what do you mean by "default csv".

**Comment by Anantkprajapati** [comment]
Hello @tmotyl - it's cause of the attribute which is missing in magento. 

So, there is no bugs related to this

Thank you
