### ISSUE TITLE
Magento 2.3

### ISSUE THREAD

**Issue by domfitty** [macopedia/magmi-m2#42]
After upgrading Magento dev environmnet to 3.1 version I got following error using magmi.
Tried to upload a fresh version of magmi and it worked until first configuration.
When I save the magento parameters I got the following errors.
I also noticed that user xxxxxx'@'localhost IS NOT the one I used during configuration

Fatal error: Uncaught PDOException: SQLSTATE[28000] [1045] Access denied for user 'xxxxxx'@'localhost' (using password: NO) in 
****/magmi/inc/dbhelper.class.php:58 Stack trace: #0 ****
/magmi/inc/dbhelper.class.php(58): PDO->__construct('mysql:host=loca...', NULL, NULL, Array) #1 ****/magmi/inc/magmi_engine.php(518): DBHelper->initDb('localhost', 'magento', NULL, NULL, '3306', NULL, 'net', false) #2 ****/magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(35): Magmi_Engine->connectToMagento() #3 ****/magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(105): Magmi_ReindexingPlugin->initIndexList() #4 ****/magmi/plugins/base/general/reindex/options_panel.php(20): Magmi_ReindexingPlugin->getIndexList() #5 
***/magmi/plugins/inc/magmi_plugin.php(95): require('/home/paol in ***/magmi/inc/dbhelper.class.php on line 58

**Comment by CalzaFino** [comment]
Same "Access denied" error using Magento 2.3.2
