### ISSUE TITLE
login problem with Magento 2.3.2

### ISSUE THREAD

**Issue by gandrap** [macopedia/magmi-m2#45]
I am having problem with login to magmi after upgrading to Magento 2.3.2. Tried also with fresh installation of Magento, same problem. 
When I enter credentials from Magento admin, magmi asking me again, like it is wrong password.

**Comment by abbatis** [comment]
Hi @gandrap, It seems that Magmi can't find your Magento 2 database credentials, which means it won't be able to authenticate you using Magento admin credentials. Therefore, try default username and password: `u: magmi / p: magmi`. Remember to configure your profile after you log in so that you'll be able to use Magento credentials to login afterwards.

**Comment by gandrap** [comment]
@abbatis Hi, I tried that, credentials are ok. I turned off magmi_auth, and I can use Magmi. Create/update products are working.  I think that Magento change something with login, maybe encryption or something like that in ver. 2.3.2

**Comment by CalzaFino** [comment]
@gandrap, Can you please give more details how are making it work? I did try commenting out 

> return $auth->authenticate(); on security.php but still not able to login.

What Magmi release are you using?

**Comment by gandrap** [comment]
@CalzaFino Magmi is magmi-m2-200.7.24. I Disable method validatePass() in magmi_auth.php, actually I change this method to always return true. Because I think that method is problem, $cecheck or $eecheck are not returning hashed string that is like in Magento database.

**Comment by TsaiEvgenii** [comment]
Hi, try to use it https://github.com/macopedia/magmi-m2/pull/47/commits/528fbac4f3cb430e44e0686f7dfeb88f7d6edc8d

**Comment by gandrap** [comment]
@TsaiEvgenii Hi, it didn't work for me. method getArgonHash() is not returning same result as $hash[0]

**Comment by tmotyl** [comment]
Released a fix in tag: 200.7.25, is also published to packagist too.

**Comment by deepanshu27193** [comment]
I need to revert it to old version to make the auth login work otherwise 500 server error at my side.
My Magento version 2.3.0.

**Comment by gfxguru** [comment]
does not fix login
