### ISSUE TITLE
Media additional images are not importing 

### ISSUE THREAD

**Issue by lalitmalav** [macopedia/magmi-m2#51]
I'm trying to import products into Magento 2 via magmi extension .

but Media Additional_images are not importing  http://prntscr.com/p2koio ?

Please review and let me know Is the column name correct AS per magmi import ?

your help would be appreciated.

**Comment by mrhambley** [comment]
Did you ever manage to get this working?

**Comment by mrhambley** [comment]
If anyone else finds this, the "media_gallery" (or "additional_images") column needs to be called "gallery".
Once renamed it works.
