### ISSUE TITLE
Field 'entity_id' doesn't have a default value

### ISSUE THREAD

**Issue by KrizzyB** [macopedia/magmi-m2#7]
On a test run of 340 items, all items failed with the error: "General error: 1364 Field 'entity_id' doesn't have a default value - ERROR ON RECORD #"

If this a Magmi error or a general SQL issue?

Magento v2.1.9

**Comment by tmotyl** [comment]
can you try again after disabling MySQL strict mode?

**Comment by KrizzyB** [comment]
That appears to have done something, now I have a new error for all 340 items:

"Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`catalog_product_entity`, CONSTRAINT `CATALOG_PRODUCT_ENTITY_ENTITY_ID_SEQUENCE_PRODUCT_SEQUENCE_VALUE` FOREIGN KEY (`entity_id`) REFERENCES `sequence_product` (`sequence_value`) ON ) - ERROR ON RECORD #"

**Comment by tmotyl** [comment]
can you provide a minimal csv which can be used to reproduce the issue? Which version of Magento 2 are you using? which version of MySQL are you using?
Seems related to https://github.com/magento/magento2/issues/6101
I have tested the current magmi for M2 version with Magento 2 CE only, so it might be also related with EE version.

**Comment by KrizzyB** [comment]
Magento: 2.1.9 EE
MySQL: 5.7.19-0ubuntu0.16.04.1
CSV: [magento-products-test-csv.zip](https://github.com/macopedia/magmi-git/files/1372404/magento-products-test-csv.zip)

**Comment by tmotyl** [comment]
@KrizzyB I've tested the file provided by you in Magento 2.2 CE and it worked well. 
I don't have Magento 2.1.9 EE at hand right now, so I can't reproduce it.
Would be great if you could investigate the issue a little bit further, and provide a pull request.
Thanks!

**Comment by udayakumar-ziffity** [comment]
I am getting the same issue "Entity_id does not have default value".
But my Magento is an enterprise edition v2.1.9. Magento's default import is very slow.
Do I need make any changes in the code / config level to work with EE?

**Comment by nileshti** [comment]
@@udayakumar-ziffity If you are using Magento EE, then need to enable flag. i.e. [MAGENTO]
version = "2.1.x EE".
Unless if you not specified EE it will treat as CE. As there are different aspects to handle EE.
I faced same issue and with the help of this solution products imported successfully.

**Comment by Devarajperumal** [comment]
Thanks, @nileshti . I am using Magento API for export and import.
