### ISSUE TITLE
SQLSTATE[HY000]: General error

### ISSUE THREAD

**Issue by vartikaongraph** [macopedia/magmi-m2#82]
I was getting "Invalid Store value" error while import even though my product csv is correct as I am able to import products with same csv using magento default import option.
After that I commented store validation condition to check the functionality further. But now I'm getting this error for each product.
"SKU 301-PB-131-RX - 2 SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'Yes' for column 'value' at row 14 - ERROR ON RECORD #1"

Note - 
1. Same csv file working fine with magento default import option
2. Using Magento version 2.3.4

**Comment by tmotyl** [comment]
Hi
Magmi import format is different then default magento import.

**Comment by vartikaongraph** [comment]
So how do I know that which format magmi will accept?

**Comment by tmotyl** [comment]
http://wiki.magmi.org/index.php/Import_new_products
